### ISSUE TITLE
Can we deprecate `durationRange` and `imputeDuration`?

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#411]
Hi @daniprietoalhambra @ajoedicke @tiozab @albertpratsu

We have an argument used to impute (usually eliminate) if a drug_exposure has a length out of range (usually 0 to Inf). As far as I know this is not used by any user as everyone uses the default options: to drop and range between 0 to Inf. 
To check this it takes a while and it is computationally expensive.
Would you consider that is reasonable to eliminate the option and basically drop the prescriptions that end date is missing or before than start date?

**Comment by daniprietoalhambra** [comment]
I'd be happy with that. It sounds like an unlikely usable thing anyways

**Comment by tiozab** [comment]
good question, depends a bit how ETL of the individual database is handling end_dates but since it is a required variable they will put something (for good or for bad). But yes, so far in my one study I am also using the defaults, so cannot really say if it would be needed in another scenario (probably more for complex studies than off the shelf?) however, if the input data is no good that imputation is needed, maybe better not to carry out the study at all ;-) so yes, maybe was a bit overengineered to offer that option and happy as well to drop it, durations can always be filtered later to fit a desired length if needed, for imputation this is obviously not the case to happen later, but I still think data quality checks should have taken care of that before it comes to analysis stage, so that no imputation should be needed.

**Comment by catalamarti** [comment]
hi @xihang-chen can you deprecate those two arguments in:
- generateDrugUtilisationCohortSet
- generateAtcCohortSet
- generateIngredientCohortSet
