### ISSUE TITLE
summariseDrugRestart

### ISSUE THREAD

**Issue by xihang-chen** [darwin-eu-dev/DrugUtilisation#511]
- window -> followUpDays = Inf
- censorDate = NULL
https://github.com/darwin-eu-dev/DrugUtilisation/tree/summarise_drug_restart

**Comment by catalamarti** [comment]
should indexDate be a parameter? @nmercadeb @edward-burn

**Comment by catalamarti** [comment]
maybe `treatmentStartDate` and `treatmentEndDate`? otherwise it is weird that we rely in cohort_start_date for restart of the treatment (without having it as a parameter) but at the same time we have a parameter called indexDate = "cohort_end_date" to see the start of the analysis.

i would say that or we have both parameters or we dont have any, but having just one it is weird @nmercadeb @edward-burn

**Comment by catalamarti** [comment]
agreed to remove indexDate as argument @edward-burn @nmercadeb
